DROP TABLE IF EXISTS SYMBOL CASCADE;
DROP TABLE IF EXISTS PRICE;
DROP TABLE IF EXISTS EXCHANGE CASCADE;
DROP VIEW IF EXISTS V_SYMBOL_INFO;
DROP VIEW IF EXISTS V_LATEST_SYMBOL_INFO;
DROP TABLE IF EXISTS USER_ENTITY CASCADE;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS REFRESH_TOKEN;