database:
  port: 5432
  host: "localhost"
  name: "finance_app"
  user: "finance_user"
  password: "YOUR_DB_PASSWORD"
api:
  twelveData:
    host: "https://api.twelvedata.com"
    timeout: "2m"
    apiKey: "YOUR_API_KEY"
    rateLimit: 8
logs:
  level: "DEBUG"
  path: "logs.txt"
server:
  port: "8090"
  readTimeoutSec: 10
  writeTimeoutSec: 60
cache:
  symbolTtl: "1h"