database:
  port: 5432
  host: "localhost"
  name: "finance_app"
  user: "finance_user"
api:
  twelveData:
    host: "https://api.twelvedata.com"
    timeout: "2m"
    rateLimit: 8
logs:
  level: "DEBUG"
  path: "logs.txt"
server:
  prefork: false
  environment: "Dev"
  port: "8090"
  readTimeout: "10s"
  writeTimeout: "60s"
cache:
  symbolTtl: "1h"
jwt:
  expiry_timeout: "15m"
  refresh_timeout_days: 30