definitions:
  handler.CommonResponse:
    properties:
      authErrors:
        items:
          $ref: '#/definitions/model.AuthError'
        type: array
      code:
        type: integer
      message:
        type: string
    type: object
  model.AuthError:
    properties:
      field:
        type: string
      rule:
        type: string
    type: object
  model.Exchange:
    properties:
      country:
        type: string
      mic_code:
        type: string
      name:
        type: string
      timezone:
        type: string
    type: object
  model.Price:
    properties:
      close:
        type: string
      date:
        type: string
      high:
        type: string
      low:
        type: string
      open:
        type: string
      volume:
        type: string
    type: object
  model.SignIn:
    properties:
      login:
        maxLength: 255
        minLength: 3
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
    required:
      - login
      - password
    type: object
  model.SignUp:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
      - email
      - password
      - username
    type: object
  model.SuccessfulAuthentication:
    properties:
      token:
        type: string
    type: object
  model.Symbol:
    properties:
      currency:
        type: string
      currency_base:
        type: string
      currency_quote:
        type: string
      exchanges:
        items:
          $ref: '#/definitions/model.Exchange'
        type: array
      name:
        type: string
      symbol:
        type: string
      type:
        type: string
      values:
        items:
          $ref: '#/definitions/model.Price'
        type: array
    required:
      - symbol
    type: object
  model.UpdateSymbol:
    properties:
      currency:
        type: string
      currency_base:
        type: string
      currency_quote:
        type: string
      exchanges:
        items:
          $ref: '#/definitions/model.Exchange'
        type: array
      name:
        type: string
      symbol:
        type: string
      type:
        type: string
      values:
        items:
          $ref: '#/definitions/model.Price'
        type: array
    required:
      - symbol
    type: object
info:
  contact: { }
  description: Finance REST API for equities, fx and crypto rates.
  title: Finance API
  version: "1.0"
paths:
  /api/v1/symbols:
    get:
      description: Get all available latest symbols
      operationId: get-symbols
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            items:
              $ref: '#/definitions/model.Symbol'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "404":
          description: Data not found
          schema:
            $ref: '#/definitions/handler.CommonResponse'
      security:
        - ApiKeyAuth:
            - client
            - admin
      summary: GetSymbols
      tags:
        - Symbols
    post:
      consumes:
        - application/json
      description: Add new symbol data
      operationId: add-symbols
      parameters:
        - description: New symbol data
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/model.Symbol'
      produces:
        - application/json
      responses:
        "200":
          description: Add successfully
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "400":
          description: Client request errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "500":
          description: Internal server errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
      security:
        - ApiKeyAuth:
            - client
            - admin
      summary: AddSymbols
      tags:
        - Symbols
    put:
      consumes:
        - application/json
      description: Update symbol data
      operationId: update-symbols
      parameters:
        - description: Update symbol data
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/model.UpdateSymbol'
      produces:
        - application/json
      responses:
        "200":
          description: Add successfully
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "400":
          description: Client request errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "500":
          description: Internal server errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
      security:
        - ApiKeyAuth:
            - admin
      summary: UpdateSymbols
      tags:
        - Symbols
  /api/v1/symbols/{symbol}:
    delete:
      description: Delete data for symbol
      operationId: delete-symbol
      produces:
        - application/json
      responses:
        "200":
          description: Deleted successfully
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "400":
          description: Client request errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "404":
          description: Client request errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "500":
          description: Internal server errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
      security:
        - ApiKeyAuth:
            - admin
      summary: DeleteSymbol
      tags:
        - Symbols
    get:
      description: Get latest data for particular symbol
      operationId: get-symbol
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            items:
              $ref: '#/definitions/model.Symbol'
            type: array
        "400":
          description: Client request error
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "404":
          description: Client request error
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.CommonResponse'
      security:
        - ApiKeyAuth:
            - client
            - admin
      summary: GetSymbol
      tags:
        - Symbols
  /auth/refresh:
    get:
      description: Refresh auth token
      operationId: refresh-token
      produces:
        - application/json
      responses:
        "200":
          description: Response with jwt token
          schema:
            $ref: '#/definitions/model.SuccessfulAuthentication'
        "400":
          description: Wrong refresh token
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "500":
          description: Internal server errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
      summary: Refresh
      tags:
        - Auth
  /auth/signin:
    put:
      consumes:
        - application/json
      description: Authenticate user
      operationId: sign-in
      parameters:
        - description: Authentication user data
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/model.SignIn'
      produces:
        - application/json
      responses:
        "200":
          description: Response with jwt token
          schema:
            $ref: '#/definitions/model.SuccessfulAuthentication'
        "400":
          description: Wrong user data
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "401":
          description: Wrong credentials
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "500":
          description: Internal server errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
      summary: SignIn
      tags:
        - Auth
  /auth/signup:
    put:
      consumes:
        - application/json
      description: Register new user
      operationId: sign-up
      parameters:
        - description: New user data
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/model.SignUp'
      produces:
        - application/json
      responses:
        "200":
          description: New user created successfully
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "400":
          description: Wrong user data
          schema:
            $ref: '#/definitions/handler.CommonResponse'
        "500":
          description: Internal server errors
          schema:
            $ref: '#/definitions/handler.CommonResponse'
      summary: SignUp
      tags:
        - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    scopes:
      admin: ' Grants read and write access to resources'
      client: ' Grants read access to resources'
    type: apiKey
swagger: "2.0"
